#ifndef COLOR_H
#define COLOR_H
#include"tgaimage.h"
#include"Math.h"
enum BLEND_OP {
	BLEND_OP_ADD = 1,
	BLEND_OP_SUBTRACT = 2,
	BLEND_OP_REV_SUBTRACT = 3,
	BLEND_OP_MIN = 4,
	BLEND_OP_MAX = 5
};

enum BLEND_FACTOR {
	BLEND_FACTOR_ZERO = 1,
	BLEND_FACTOR_ONE = 2,
	BLEND_FACTOR_SRC_COLOR = 3,
	BLEND_FACTOR_INV_STR_COLOR = 4,
	BLEND_FACTOR_SRC_ALPHA = 5,
	BLEND_FACTOR_INV_SRC_ALPHA = 6,
	BLEND_FACTOR_DEST_ALPHA = 7,
	BLEND_FACTOR_INV_DEST_ALPHA = 8,
	BLEND_FACTOR_DEST_COLOR = 9,
	BLEND_FACTOR_INV_DEST_COLOR = 10,
	BLEND_FACTOR_SRC_ALPHA_SAT = 11,
	BLEND_FACTOR_BLEND_FACTOR = 12,
	BLEND_FACTOR_INV_BLEND_FACTOR = 13
};


TGAColor OMSetBlendState(TGAColor  src, TGAColor  dst, BLEND_OP op, BLEND_FACTOR factorSrc, BLEND_FACTOR factorDst);

#endif // !COLOR_H
